DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    EMAIL TEXT,
    AGE INT,
    PHONE TEXT
   
);

INSERT INTO STUDENT(NAME,AGE,PHONE,EMAIL)
VALUES ('Alex','alex@gmail.com',20,'010-222-111');

SELECT * from STUDENT;
DELETE FROM STUDENT WHERE id =3;